[project]
name = "backend"
version = "0.1.0"
description = "Todo API Backend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.124.0",
    "pydantic-settings>=2.12.0",
    "uvicorn>=0.38.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src"]
